//! A single lexical item.

/// The different types of Token. Some token kinds require additional data,
/// and will carry it here.
#[derive(Debug, PartialEq)]
pub enum TokenKind {
    /// A single open parenthese.
    OpenParen,
    /// A single closed parenthese.
    CloseParen,
    /// An identifier.
    Ident(String),
    /// An integer literal.
    IntegerLiteral(i64),
    /// A floating point literal.
    FloatLiteral(f64),
}

/// The location of a token in an input stream.
#[derive(Debug, PartialEq, Clone, Copy)]
pub struct Location(pub usize);

impl Location {
    /// Get the length of the span from the current location to the end
    /// location.
    pub fn span_to(&self, end_loc: Location) -> Span {
        Span(end_loc.0 - self.0 + 1)
    }
}

/// The span of a token in an input stream.
#[derive(Debug, PartialEq)]
pub struct Span(pub usize);

/// Tokens, generated by the lexer. Every token has a location in the input
/// stream, a span indicating how large they are, and a type that potentially
/// has some associated data.
#[derive(Debug, PartialEq)]
pub struct Token {
    /// The kind of token, potentially with some additional data.
    pub kind: TokenKind,
    /// The location of the token in the input stream.
    pub location: Location,
    /// The width of the token in the input stream.
    pub span: Span,
}

impl Token {
    /// Token constructor for open parentheses.
    pub fn open_paren(location: Location) -> Token {
        Token {
            kind: TokenKind::OpenParen,
            location: location,
            span: Span(1),
        }
    }

    /// Token constructor for closed parentheses.
    pub fn close_paren(location: Location) -> Token {
        Token {
            kind: TokenKind::CloseParen,
            location: location,
            span: Span(1),
        }
    }

    /// Token constructor for identifiers.
    pub fn ident<S: Into<String>>(name: S, location: Location) -> Token {
        let name: String = name.into();
        let len = name.len();

        Token {
            kind: TokenKind::Ident(name),
            location: location,
            span: Span(len),
        }
    }

    /// Token constructor for integers.
    pub fn integer(value: i64, start_loc: Location, end_loc: Location) -> Token {
        Token {
            kind: TokenKind::IntegerLiteral(value),
            location: start_loc,
            span: start_loc.span_to(end_loc),
        }
    }

    /// Token constructor for floats.
    pub fn float(value: f64, start_loc: Location, end_loc: Location) -> Token {
        Token {
            kind: TokenKind::FloatLiteral(value),
            location: start_loc,
            span: start_loc.span_to(end_loc),
        }
    }
}
